import AppKit
import ApplicationServices
import AVFoundation
import Carbon

enum InsertOutcome {
    case pasted
    case copiedToClipboard
    case secureField
}

/// Puts text at the cursor of the frontmost app and reads the current selection.
@MainActor
enum TextInserter {
    /// Marks keyboard events Saywrite posts itself, so the hotkey monitor can ignore them.
    static let syntheticEventTag: Int64 = 0x5357_5752 // "SWWR"

    /// Pasteboard types that tell clipboard managers not to record this entry.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// `onPasted` runs right after ⌘V was sent, before the clipboard is restored, so feedback
    /// (sound, closing the panel) is not delayed by the restore wait.
    static func insert(_ text: String, onPasted: (() -> Void)? = nil) async -> InsertOutcome {
        let pasteboard = NSPasteboard.general
        if isSecureInputActive() { return .secureField }
        guard focusedElement() != nil else {
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            return .copiedToClipboard
        }
        let saved = savePasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setString("", forType: type) }
        pasteboard.writeObjects([item])
        let changeCount = pasteboard.changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_V))
        onPasted?()
        // Slow apps (Electron) read the clipboard late; restore only after they had time.
        try? await Task.sleep(nanoseconds: 800_000_000)
        if pasteboard.changeCount == changeCount, let saved {
            restorePasteboard(saved)
        }
        return .pasted
    }

    /// Undo the last edit in the frontmost app (used to swap the inserted text for the original).
    static func undo() {
        postCommand(key: CGKeyCode(kVK_ANSI_Z))
    }

    /// The selected text in the frontmost app, via Accessibility or, as a fallback, a simulated ⌘C.
    static func selectedText() async -> String? {
        if let element = focusedElement() {
            var value: CFTypeRef?
            let status = AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &value)
            if status == .success {
                // A real "nothing selected". ⌘C would copy the whole line in some editors.
                guard let text = value as? String, !text.isEmpty else { return nil }
                return text
            }
        }
        let pasteboard = NSPasteboard.general
        let saved = savePasteboard()
        let before = pasteboard.changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_C))
        var text: String?
        for _ in 0..<15 {
            try? await Task.sleep(nanoseconds: 30_000_000)
            if pasteboard.changeCount != before {
                text = pasteboard.string(forType: .string)
                break
            }
        }
        // Only touch the clipboard again if the copy actually happened.
        if pasteboard.changeCount != before, let saved { restorePasteboard(saved) }
        guard let text, !text.isEmpty else { return nil }
        return text
    }

    // MARK: - Helpers

    private static func isSecureInputActive() -> Bool {
        if IsSecureEventInputEnabled() { return true }
        guard let element = focusedElement() else { return false }
        var subrole: CFTypeRef?
        AXUIElementCopyAttributeValue(element, kAXSubroleAttribute as CFString, &subrole)
        return (subrole as? String) == kAXSecureTextFieldSubrole
    }

    private static func focusedElement() -> AXUIElement? {
        let system = AXUIElementCreateSystemWide()
        // A hung app must not freeze Saywrite (and with it the hotkey tap).
        AXUIElementSetMessagingTimeout(system, 0.3)
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value, CFGetTypeID(value) == AXUIElementGetTypeID()
        else { return nil }
        return (value as! AXUIElement)
    }

    private static func postCommand(key: CGKeyCode) {
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.userData = syntheticEventTag
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        for event in [down, up] {
            event?.flags = .maskCommand
            event?.setIntegerValueField(.eventSourceUserData, value: syntheticEventTag)
            event?.post(tap: .cghidEventTap)
        }
    }

    private typealias SavedItem = [(NSPasteboard.PasteboardType, Data)]

    /// Nil when the clipboard holds something too big or lazy (file promises) to copy safely;
    /// then it is not restored rather than half-restored.
    private static func savePasteboard() -> [SavedItem]? {
        let items = NSPasteboard.general.pasteboardItems ?? []
        var saved: [SavedItem] = []
        var total = 0
        for item in items {
            var entries: SavedItem = []
            for type in item.types {
                if type.rawValue.contains("promise") { return nil }
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                if total > 20_000_000 { return nil }
                entries.append((type, data))
            }
            saved.append(entries)
        }
        return saved
    }

    private static func restorePasteboard(_ items: [SavedItem]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

/// Microphone and Accessibility permission checks.
@MainActor
enum Permissions {
    static var accessibilityGranted: Bool { AXIsProcessTrusted() }

    static func requestAccessibility() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    static var microphoneStatus: AVAuthorizationStatusWrapper { AVAuthorizationStatusWrapper.current }

    static func requestMicrophone() async -> Bool {
        await AVAuthorizationStatusWrapper.request()
    }

    static func openAccessibilitySettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")!)
    }

    static func openMicrophoneSettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone")!)
    }
}

enum AVAuthorizationStatusWrapper {
    case granted, denied, undetermined

    static var current: AVAuthorizationStatusWrapper {
        switch AVCaptureDevice.authorizationStatus(for: .audio) {
        case .authorized: return .granted
        case .notDetermined: return .undetermined
        default: return .denied
        }
    }

    static func request() async -> Bool {
        await AVCaptureDevice.requestAccess(for: .audio)
    }
}
