import AppKit
import SaywriteCore
import ApplicationServices
import AVFoundation
import Carbon
import os

enum InsertOutcome {
    case pasted
    case copiedToClipboard
    case secureField
    /// Secure event input is on (some app holds it) and the focus is no known text field: the text
    /// was put on the clipboard instead of being pasted or discarded.
    case copiedSecureInput
    /// Another app came to the front while the text was being prepared: copied instead of pasted.
    case appChanged
}

/// Puts text at the cursor of the frontmost app and reads the current selection.
///
/// Accessibility queries run off the main thread: a slow or hung app can take up to the messaging
/// timeout per call, and the main thread also serves the hotkey event tap, which every key press in
/// the system waits for.
@MainActor
enum TextInserter {
    /// Marks keyboard events Saywrite posts itself, so the hotkey monitor can ignore them.
    nonisolated static let syntheticEventTag: Int64 = 0x5357_5752 // "SWWR"

    /// Pasteboard types that tell clipboard managers not to record this entry.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// The user's own clipboard while one of our pastes is still waiting to restore it. A second
    /// insert in that window must not save our temporary text as "the user's clipboard".
    private static var userClipboard: [SavedItem]??
    private static var pasteGeneration = 0
    private static var lastWrittenChangeCount = -1

    /// Whether ⌘Z in the target of the last paste reliably undoes exactly that paste.
    private(set) static var lastPasteSupportsUndo = false

    private struct Probe: Sendable {
        var elementIsSecure: Bool
        var secureInputEnabled: Bool
        var target: PasteTarget
    }

    /// Whether any app holds secure event input. System-wide: not proof that the focus is a password field.
    nonisolated static var secureInputActive: Bool { IsSecureEventInputEnabled() }

    /// Whether the focused element is a password field, for a check before the dictation is processed.
    static func focusIsSecureField() async -> Bool {
        let app = NSWorkspace.shared.frontmostApplication
        let electron = app.map(isElectron) ?? false
        let bundleID = app?.bundleIdentifier ?? ""
        let pid = app?.processIdentifier ?? 0
        return await Task.detached {
            // Switch the tree on early so it has built by the time the user stops speaking.
            enableManualAccessibility(bundleID: bundleID, pid: pid, isElectron: electron)
            return focusedElement().map(isSecureField) == true
        }.value
    }

    private nonisolated static let manualAXPids = OSAllocatedUnfairLock(initialState: Set<pid_t>())

    /// Ask Chromium/Electron to build their accessibility tree, once per process: keeping the tree on
    /// makes those apps slower, so it is not repeated on every paste.
    private nonisolated static func enableManualAccessibility(bundleID: String, pid: pid_t, isElectron: Bool) {
        guard pid != 0, PasteTargetRules.shouldEnableManualAccessibility(bundleID: bundleID, isElectron: isElectron),
              manualAXPids.withLock({ $0.insert(pid).inserted }) else { return }
        let application = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(application, 0.3)
        AXUIElementSetAttributeValue(application, "AXManualAccessibility" as CFString, kCFBooleanTrue)
    }

    /// Everything insert() needs to know from Accessibility, gathered on a background thread.
    private nonisolated static func probe(bundleID: String, pid: pid_t, isElectron: Bool) -> Probe {
        // Chromium and Electron build their accessibility tree only on request; without it a
        // password field there looks like no field at all.
        enableManualAccessibility(bundleID: bundleID, pid: pid, isElectron: isElectron)
        let element = focusedElement()
        let elementIsSecure = element.map(isSecureField) == true
        let secureInput = IsSecureEventInputEnabled()
        if elementIsSecure { return Probe(elementIsSecure: true, secureInputEnabled: secureInput, target: .none) }
        var focus: PasteTargetRules.Focus?
        if let element {
            var role: CFTypeRef?
            AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role)
            var settable: DarwinBoolean = false
            AXUIElementIsAttributeSettable(element, kAXSelectedTextRangeAttribute as CFString, &settable)
            let roleName = role as? String
            let editable = PasteTargetRules.needsEditableDocumentCheck(role: roleName, selectedRangeSettable: settable.boolValue)
                && isEditableDocument(element)
            focus = PasteTargetRules.Focus(role: roleName, selectedRangeSettable: settable.boolValue, editableDocument: editable)
        }
        return Probe(
            elementIsSecure: false, secureInputEnabled: secureInput,
            target: PasteTargetRules.decide(bundleID: bundleID, focus: focus, isElectron: isElectron))
    }

    /// WebKit marks an editable document (Mail compose, rich-text editors in an iframe) with an
    /// editable ancestor or a settable value; a plain page has neither.
    private nonisolated static func isEditableDocument(_ element: AXUIElement) -> Bool {
        for attribute in ["AXEditableAncestor", "AXHighestEditableAncestor"] {
            var value: CFTypeRef?
            if AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success, value != nil { return true }
        }
        var valueSettable: DarwinBoolean = false
        AXUIElementIsAttributeSettable(element, kAXValueAttribute as CFString, &valueSettable)
        return valueSettable.boolValue
    }

    static func isElectron(_ app: NSRunningApplication) -> Bool {
        guard let url = app.bundleURL else { return false }
        return FileManager.default.fileExists(atPath: url.appendingPathComponent("Contents/Frameworks/Electron Framework.framework").path)
    }

    /// `expectedApp`: the app the dictation was started in. If another app is in front by now, the
    /// text is copied instead of landing in the wrong window.
    /// `onPasted` runs right after ⌘V was sent, before the clipboard is restored, so feedback
    /// (sound, closing the panel) is not delayed by the restore wait.
    /// `recordsUndo` is false for a paste that belongs to no running dictation ("Paste last"), so it
    /// does not change whether the pill of another dictation offers "Original".
    static func insert(_ text: String, expectedApp: String? = nil, recordsUndo: Bool = true, onPasted: (() -> Void)? = nil) async -> InsertOutcome {
        let pasteboard = NSPasteboard.general
        // Only a missing frontmost app means "nowhere to paste" up front; Electron apps (Slack,
        // VS Code, Discord) often expose no focused element but accept ⌘V.
        guard let app = NSWorkspace.shared.frontmostApplication else {
            copy(text)
            return .copiedToClipboard
        }
        let bundleID = app.bundleIdentifier ?? ""
        if let expectedApp, bundleID != expectedApp {
            Debug.log("paste target changed from \(expectedApp) to \(bundleID): copying")
            copy(text)
            return .appChanged
        }
        let electron = isElectron(app)
        let pid = app.processIdentifier
        let probed = await Task.detached { probe(bundleID: bundleID, pid: pid, isElectron: electron) }.value
        let target = probed.target
        switch SecureInputRules.decide(elementIsSecure: probed.elementIsSecure, secureInputEnabled: probed.secureInputEnabled, target: target) {
        case .secureField: return .secureField
        case .copyOnly:
            Debug.log("secure input active, focus unknown in \(bundleID): copying")
            copy(text)
            return .copiedSecureInput
        case .proceed: break
        }
        Debug.log("paste target \(target) in \(bundleID)")
        if recordsUndo { lastPasteSupportsUndo = target == .textField }
        guard target != .none else {
            copy(text)
            return .copiedToClipboard
        }
        // The probe ran in the background: the user may have switched apps meanwhile.
        guard NSWorkspace.shared.frontmostApplication?.processIdentifier == app.processIdentifier else {
            copy(text)
            return .appChanged
        }
        // Save the user's clipboard, unless one of our own pastes is still pending (then its saved
        // copy is the real one). If the user copied something meanwhile, that is the new original.
        if userClipboard == nil || pasteboard.changeCount != lastWrittenChangeCount {
            userClipboard = .some(savePasteboard())
        }
        pasteGeneration += 1
        let generation = pasteGeneration
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setString("", forType: type) }
        pasteboard.writeObjects([item])
        let changeCount = pasteboard.changeCount
        lastWrittenChangeCount = changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_V))
        onPasted?()
        // Restore only after the app had time to read the clipboard. Electron apps and terminals
        // (blind targets) read it noticeably later than native text fields.
        let wait: UInt64 = target == .blind ? 1_500_000_000 : 800_000_000
        try? await Task.sleep(nanoseconds: wait)
        // Only the latest paste restores, and only if nobody copied something else meanwhile.
        guard generation == pasteGeneration else { return .pasted }
        if pasteboard.changeCount == changeCount, case .some(.some(let saved)) = userClipboard {
            restorePasteboard(saved)
        }
        userClipboard = nil
        return .pasted
    }

    /// Puts text on the clipboard for a manual ⌘V, marked so clipboard managers do not record it.
    static func copy(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setString("", forType: type) }
        pasteboard.writeObjects([item])
    }

    /// Gives the user's clipboard back when the app quits while a paste is still waiting to restore it.
    static func restorePendingClipboard() {
        guard case .some(.some(let saved)) = userClipboard,
              NSPasteboard.general.changeCount == lastWrittenChangeCount else { return }
        restorePasteboard(saved)
        userClipboard = nil
    }

    /// The selection of the focused element as it is now, to check a rewrite still targets it.
    static func currentSelection() async -> SelectionReading {
        await Task.detached { selectionViaAccessibility() }.value
    }

    /// Undo the last edit in the frontmost app (used to swap the inserted text for the original).
    static func undo() {
        postCommand(key: CGKeyCode(kVK_ANSI_Z))
    }

    /// The selected text in the frontmost app, via Accessibility or, as a fallback, a simulated ⌘C.
    static func selectedText() async -> String? {
        switch await Task.detached(operation: { selectionViaAccessibility() }).value {
        case .text(let text): return text
        // A real "nothing selected". ⌘C would copy the whole line in some editors.
        case .empty: return nil
        case .unavailable: break
        }
        let pasteboard = NSPasteboard.general
        // During a pending paste restore the clipboard holds our own text; keep the real original.
        let pendingOriginal = userClipboard
        // .some(nil): the original could not be saved (too large); never restore our own text then.
        let saved: [SavedItem]? = pendingOriginal != nil ? pendingOriginal! : savePasteboard()
        pasteGeneration += 1
        userClipboard = nil
        let before = pasteboard.changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_C))
        var text: String?
        for _ in 0..<15 {
            try? await Task.sleep(nanoseconds: 30_000_000)
            if pasteboard.changeCount != before {
                text = pasteboard.string(forType: .string)
                break
            }
        }
        // Restore when the copy happened, and always when we took over a pending paste restore
        // (its restore was cancelled above, so the user's original must come back now).
        let tookOverPending = pendingOriginal != nil
        if pasteboard.changeCount != before || tookOverPending, let saved { restorePasteboard(saved) }
        guard let text, !text.isEmpty else { return nil }
        return text
    }

    // MARK: - Helpers

    private nonisolated static func selectionViaAccessibility() -> SelectionReading {
        guard let element = focusedElement() else { return .unavailable }
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &value) == .success else {
            return .unavailable
        }
        guard let text = value as? String, !text.isEmpty else { return .empty }
        return .text(text)
    }

    private nonisolated static func isSecureField(_ element: AXUIElement) -> Bool {
        var subrole: CFTypeRef?
        AXUIElementCopyAttributeValue(element, kAXSubroleAttribute as CFString, &subrole)
        return (subrole as? String) == kAXSecureTextFieldSubrole
    }

    private nonisolated static func focusedElement() -> AXUIElement? {
        let system = AXUIElementCreateSystemWide()
        // A hung app must not keep the background probe (and with it the paste) waiting long.
        AXUIElementSetMessagingTimeout(system, 0.3)
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value, CFGetTypeID(value) == AXUIElementGetTypeID()
        else { return nil }
        return (value as! AXUIElement)
    }

    private static func postCommand(key: CGKeyCode) {
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.userData = syntheticEventTag
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        for event in [down, up] {
            event?.flags = .maskCommand
            event?.setIntegerValueField(.eventSourceUserData, value: syntheticEventTag)
            event?.post(tap: .cghidEventTap)
        }
    }

    private typealias SavedItem = [(NSPasteboard.PasteboardType, Data)]

    /// Nil when the clipboard holds something too big or lazy (file promises) to copy safely;
    /// then it is not restored rather than half-restored.
    private static func savePasteboard() -> [SavedItem]? {
        let items = NSPasteboard.general.pasteboardItems ?? []
        var saved: [SavedItem] = []
        var total = 0
        for item in items {
            var entries: SavedItem = []
            for type in item.types {
                if type.rawValue.contains("promise") { return nil }
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                if total > 20_000_000 { return nil }
                entries.append((type, data))
            }
            saved.append(entries)
        }
        return saved
    }

    private static func restorePasteboard(_ items: [SavedItem]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

/// Microphone and Accessibility permission checks.
@MainActor
enum Permissions {
    static var accessibilityGranted: Bool { AXIsProcessTrusted() }

    static func requestAccessibility() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    static var microphoneStatus: AVAuthorizationStatusWrapper { AVAuthorizationStatusWrapper.current }

    static func requestMicrophone() async -> Bool {
        await AVAuthorizationStatusWrapper.request()
    }

    static func openAccessibilitySettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")!)
    }

    static func openMicrophoneSettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone")!)
    }
}

enum AVAuthorizationStatusWrapper {
    case granted, denied, undetermined

    static var current: AVAuthorizationStatusWrapper {
        switch AVCaptureDevice.authorizationStatus(for: .audio) {
        case .authorized: return .granted
        case .notDetermined: return .undetermined
        default: return .denied
        }
    }

    static func request() async -> Bool {
        await AVCaptureDevice.requestAccess(for: .audio)
    }
}
