import AppKit
import SaywriteCore
import ApplicationServices
import AVFoundation
import Carbon

enum InsertOutcome {
    case pasted
    case copiedToClipboard
    case secureField
}

/// Puts text at the cursor of the frontmost app and reads the current selection.
@MainActor
enum TextInserter {
    /// Marks keyboard events Saywrite posts itself, so the hotkey monitor can ignore them.
    static let syntheticEventTag: Int64 = 0x5357_5752 // "SWWR"

    /// Pasteboard types that tell clipboard managers not to record this entry.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// `onPasted` runs right after ⌘V was sent, before the clipboard is restored, so feedback
    /// (sound, closing the panel) is not delayed by the restore wait.
    /// The user's own clipboard while one of our pastes is still waiting to restore it. A second
    /// insert in that window must not save our temporary text as "the user's clipboard".
    private static var userClipboard: [SavedItem]??
    private static var pasteGeneration = 0
    private static var lastWrittenChangeCount = -1

    /// Whether ⌘Z in the target of the last paste reliably undoes exactly that paste.
    private(set) static var lastPasteSupportsUndo = false

    private enum PasteTarget { case textField, blind, none }

    /// Apps whose windows expose no accessibility text field but accept ⌘V (Electron, Chromium).
    private static let blindPasteApps: Set<String> = [
        "com.tinyspeck.slackmacgap", "com.hnc.Discord", "com.microsoft.VSCode", "com.todesktop.230313mzl4w4u92",
        "com.google.Chrome", "com.brave.Browser", "com.microsoft.edgemac", "company.thebrowser.Browser",
        "com.vivaldi.Vivaldi", "notion.id", "com.spotify.client", "md.obsidian", "com.figma.Desktop",
        "net.whatsapp.WhatsApp", "desktop.WhatsApp", "org.whispersystems.signal-desktop", "com.linear",
    ]

    /// Terminals: ⌘Z does not undo a paste there, so "Original" is not offered.
    private static let terminals: Set<String> = [
        "com.apple.Terminal", "com.googlecode.iterm2", "dev.warp.Warp-Stable", "com.mitchellh.ghostty",
        "net.kovidgoyal.kitty", "io.alacritty",
    ]

    private static let textRoles: Set<String> = [
        kAXTextFieldRole, kAXTextAreaRole, kAXComboBoxRole, "AXSearchField",
    ]

    /// Native apps with little accessibility support that still accept ⌘V.
    private static let blindPasteEditors: Set<String> = [
        "dev.zed.Zed", "com.sublimetext.4", "com.sublimetext.3", "com.jetbrains.intellij", "com.jetbrains.pycharm",
    ]

    private static func pasteTarget() -> PasteTarget {
        guard let app = NSWorkspace.shared.frontmostApplication else { return .none }
        let bundleID = app.bundleIdentifier ?? ""
        if let element = focusedElement() {
            var role: CFTypeRef?
            AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role)
            var settable: DarwinBoolean = false
            AXUIElementIsAttributeSettable(element, kAXSelectedTextRangeAttribute as CFString, &settable)
            // A web area only counts when it is editable (Mail compose, a focused input); a page or a
            // received mail in Safari/Mail is not a text field, and ⌘Z there could reopen a tab.
            let isEditableWebArea = (role as? String) == "AXWebArea" && (settable.boolValue || isEditableDocument(element))
            if textRoles.contains(role as? String ?? "") || settable.boolValue || isEditableWebArea {
                return terminals.contains(bundleID) ? .blind : .textField
            }
        }
        // Finder, the desktop, Preview: ⌘V would do nothing (or paste a file), so copy instead.
        if blindPasteApps.contains(bundleID) || blindPasteEditors.contains(bundleID) || terminals.contains(bundleID)
            || isElectron(app) {
            return .blind
        }
        return .none
    }

    /// WebKit marks an editable document (Mail compose, rich-text editors in an iframe) with an
    /// editable ancestor or a settable value; a plain page has neither.
    private static func isEditableDocument(_ element: AXUIElement) -> Bool {
        for attribute in ["AXEditableAncestor", "AXHighestEditableAncestor"] {
            var value: CFTypeRef?
            if AXUIElementCopyAttributeValue(element, attribute as CFString, &value) == .success, value != nil { return true }
        }
        var valueSettable: DarwinBoolean = false
        AXUIElementIsAttributeSettable(element, kAXValueAttribute as CFString, &valueSettable)
        return valueSettable.boolValue
    }

    private static func isElectron(_ app: NSRunningApplication) -> Bool {
        guard let url = app.bundleURL else { return false }
        return FileManager.default.fileExists(atPath: url.appendingPathComponent("Contents/Frameworks/Electron Framework.framework").path)
    }

    static func insert(_ text: String, onPasted: (() -> Void)? = nil) async -> InsertOutcome {
        let pasteboard = NSPasteboard.general
        if isSecureInputActive() { return .secureField }
        // Electron apps (Slack, VS Code, Discord) often expose no focused element but accept ⌘V,
        // so only a missing frontmost app means "nowhere to paste".
        let target = pasteTarget()
        Debug.log("paste target \(target) in \(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "-")")
        lastPasteSupportsUndo = target == .textField
        guard target != .none else {
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            return .copiedToClipboard
        }
        // Save the user's clipboard, unless one of our own pastes is still pending (then its saved
        // copy is the real one). If the user copied something meanwhile, that is the new original.
        if userClipboard == nil || pasteboard.changeCount != lastWrittenChangeCount {
            userClipboard = .some(savePasteboard())
        }
        pasteGeneration += 1
        let generation = pasteGeneration
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setString("", forType: type) }
        pasteboard.writeObjects([item])
        let changeCount = pasteboard.changeCount
        lastWrittenChangeCount = changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_V))
        onPasted?()
        // Slow apps (Electron) read the clipboard late; restore only after they had time.
        try? await Task.sleep(nanoseconds: 800_000_000)
        // Only the latest paste restores, and only if nobody copied something else meanwhile.
        guard generation == pasteGeneration else { return .pasted }
        if pasteboard.changeCount == changeCount, case .some(.some(let saved)) = userClipboard {
            restorePasteboard(saved)
        }
        userClipboard = nil
        return .pasted
    }

    /// Undo the last edit in the frontmost app (used to swap the inserted text for the original).
    static func undo() {
        postCommand(key: CGKeyCode(kVK_ANSI_Z))
    }

    /// The selected text in the frontmost app, via Accessibility or, as a fallback, a simulated ⌘C.
    static func selectedText() async -> String? {
        if let element = focusedElement() {
            var value: CFTypeRef?
            let status = AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &value)
            if status == .success {
                // A real "nothing selected". ⌘C would copy the whole line in some editors.
                guard let text = value as? String, !text.isEmpty else { return nil }
                return text
            }
        }
        let pasteboard = NSPasteboard.general
        // During a pending paste restore the clipboard holds our own text; keep the real original.
        let pendingOriginal = userClipboard
        // .some(nil): the original could not be saved (too large); never restore our own text then.
        let saved: [SavedItem]? = pendingOriginal != nil ? pendingOriginal! : savePasteboard()
        pasteGeneration += 1
        userClipboard = nil
        let before = pasteboard.changeCount
        postCommand(key: CGKeyCode(kVK_ANSI_C))
        var text: String?
        for _ in 0..<15 {
            try? await Task.sleep(nanoseconds: 30_000_000)
            if pasteboard.changeCount != before {
                text = pasteboard.string(forType: .string)
                break
            }
        }
        // Restore when the copy happened, and always when we took over a pending paste restore
        // (its restore was cancelled above, so the user's original must come back now).
        let tookOverPending = pendingOriginal != nil
        if pasteboard.changeCount != before || tookOverPending, let saved { restorePasteboard(saved) }
        guard let text, !text.isEmpty else { return nil }
        return text
    }

    // MARK: - Helpers

    private static func isSecureInputActive() -> Bool {
        if IsSecureEventInputEnabled() { return true }
        guard let element = focusedElement() else { return false }
        var subrole: CFTypeRef?
        AXUIElementCopyAttributeValue(element, kAXSubroleAttribute as CFString, &subrole)
        return (subrole as? String) == kAXSecureTextFieldSubrole
    }

    private static func focusedElement() -> AXUIElement? {
        let system = AXUIElementCreateSystemWide()
        // A hung app must not freeze Saywrite (and with it the hotkey tap).
        AXUIElementSetMessagingTimeout(system, 0.3)
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value, CFGetTypeID(value) == AXUIElementGetTypeID()
        else { return nil }
        return (value as! AXUIElement)
    }

    private static func postCommand(key: CGKeyCode) {
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.userData = syntheticEventTag
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        for event in [down, up] {
            event?.flags = .maskCommand
            event?.setIntegerValueField(.eventSourceUserData, value: syntheticEventTag)
            event?.post(tap: .cghidEventTap)
        }
    }

    private typealias SavedItem = [(NSPasteboard.PasteboardType, Data)]

    /// Nil when the clipboard holds something too big or lazy (file promises) to copy safely;
    /// then it is not restored rather than half-restored.
    private static func savePasteboard() -> [SavedItem]? {
        let items = NSPasteboard.general.pasteboardItems ?? []
        var saved: [SavedItem] = []
        var total = 0
        for item in items {
            var entries: SavedItem = []
            for type in item.types {
                if type.rawValue.contains("promise") { return nil }
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                if total > 20_000_000 { return nil }
                entries.append((type, data))
            }
            saved.append(entries)
        }
        return saved
    }

    private static func restorePasteboard(_ items: [SavedItem]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

/// Microphone and Accessibility permission checks.
@MainActor
enum Permissions {
    static var accessibilityGranted: Bool { AXIsProcessTrusted() }

    static func requestAccessibility() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    static var microphoneStatus: AVAuthorizationStatusWrapper { AVAuthorizationStatusWrapper.current }

    static func requestMicrophone() async -> Bool {
        await AVAuthorizationStatusWrapper.request()
    }

    static func openAccessibilitySettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility")!)
    }

    static func openMicrophoneSettings() {
        NSWorkspace.shared.open(URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone")!)
    }
}

enum AVAuthorizationStatusWrapper {
    case granted, denied, undetermined

    static var current: AVAuthorizationStatusWrapper {
        switch AVCaptureDevice.authorizationStatus(for: .audio) {
        case .authorized: return .granted
        case .notDetermined: return .undetermined
        default: return .denied
        }
    }

    static func request() async -> Bool {
        await AVCaptureDevice.requestAccess(for: .audio)
    }
}
